#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${1:-"$(dirname "$ROOT")/trinity_v2_github_export"}"
IGNORE_FILE="$ROOT/.github-export-ignore"

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

command -v rsync >/dev/null 2>&1 || die "rsync is required"
command -v rg >/dev/null 2>&1 || die "ripgrep (rg) is required"
[[ -f "$IGNORE_FILE" ]] || die "missing export ignore file: $IGNORE_FILE"

ROOT_REAL="$(cd "$ROOT" && pwd -P)"
DEST_PARENT="$(dirname "$DEST")"
mkdir -p "$DEST_PARENT"
DEST_REAL_PARENT="$(cd "$DEST_PARENT" && pwd -P)"
DEST_REAL="$DEST_REAL_PARENT/$(basename "$DEST")"

if [[ "$DEST_REAL" == "$ROOT_REAL" || "$DEST_REAL" == "$ROOT_REAL/"* ]]; then
  die "destination must be outside the source repo: $DEST_REAL"
fi

if [[ "$DEST_REAL" == "/" || "$DEST_REAL" == "$HOME" ]]; then
  die "refusing unsafe destination: $DEST_REAL"
fi

mkdir -p "$DEST_REAL"

rsync -a --delete \
  --exclude-from "$IGNORE_FILE" \
  "$ROOT_REAL/" "$DEST_REAL/"

find "$DEST_REAL" -name .DS_Store -type f -delete
rm -rf \
  "$DEST_REAL/.ai/.pytest_cache" \
  "$DEST_REAL/.pytest_cache"
rm -f \
  "$DEST_REAL/.ai/state/status.json" \
  "$DEST_REAL/.ai/state/verify_report.json" \
  "$DEST_REAL/.ai/state/locks.json"

# Public export sanitization. Keep the working tree untouched; only rewrite
# generated files. Path redactions are derived from this checkout at runtime so
# the export tooling can be committed without machine-specific literals.
WORKSPACE_REAL="$(dirname "$ROOT_REAL")"
HOME_REAL="$(cd "$HOME" && pwd -P)"
EXPORT_SCRIPT_REAL="$DEST_REAL/scripts/export_github.sh"

while IFS= read -r file; do
  [[ "$file" == "$EXPORT_SCRIPT_REAL" ]] && continue
  TRINITY_EXPORT_ROOT_REAL="$ROOT_REAL" \
  TRINITY_EXPORT_WORKSPACE_REAL="$WORKSPACE_REAL" \
  TRINITY_EXPORT_HOME_REAL="$HOME_REAL" \
  LC_ALL=C perl -0pi -e '
    for my $pair (
      [$ENV{TRINITY_EXPORT_ROOT_REAL}, "<trinity-root>"],
      [$ENV{TRINITY_EXPORT_WORKSPACE_REAL}, "<workspace-root>"],
      [$ENV{TRINITY_EXPORT_HOME_REAL}, "<user-home>"],
    ) {
      my ($from, $to) = @$pair;
      next unless defined $from && length $from;
      s/\Q$from\E/$to/g;
    }
    s#/Users/[^/"'"'"'`[:space:]]+#<user-home>#g;
    s#/<home>/<user>/Downloads/[^/"'"'"'`[:space:]]+#<workspace-root>#g;
    s#/<home>/<user>#<user-home>#g;
    s/\bvape[0-9]+/example_project/g;
    s/\bVape[0-9]+/Example Project/g;
    s/\bVAPE[0-9]+/EXAMPLE_PROJECT/g;
    s/\bTRINITY_[A-Z0-9_]*ULTIMAT[A-Z0-9_]*\b/TRINITY_LEGACY/g;
    s/\btrinity_[a-z0-9_]*ultimat[a-z0-9_]*\b/trinity_legacy/g;
  ' "$file"
done < <(
  rg -l --hidden --glob '!.git/**' \
    '/Users/|/<home>/<user>|[vV][aA][pP][eE][0-9]+|TRINITY_[A-Z0-9_]*ULTIMAT[A-Z0-9_]*|trinity_[a-z0-9_]*ultimat[a-z0-9_]*' \
    "$DEST_REAL" || true
)

# Recreate empty runtime placeholders so a fresh clone has the expected shape
# without carrying local audit, sessions, memory, or state.
mkdir -p \
  "$DEST_REAL/.ai/audit" \
  "$DEST_REAL/.ai/sessions/active" \
  "$DEST_REAL/.ai/sessions/archive" \
  "$DEST_REAL/.ai/memory" \
  "$DEST_REAL/.ai/state"

touch \
  "$DEST_REAL/.ai/audit/.gitkeep" \
  "$DEST_REAL/.ai/sessions/active/.gitkeep" \
  "$DEST_REAL/.ai/sessions/archive/.gitkeep" \
  "$DEST_REAL/.ai/memory/.gitkeep" \
  "$DEST_REAL/.ai/state/.gitkeep"

cat > "$DEST_REAL/.ai/audit/events.ndjson" <<'EOF'
{"ts":"2026-05-17T00:00:00Z","type":"genesis","prev_hash":"0","details":{"trinity_version":"v0.1.0","spec_pack":"v2.0.0","project":"trinity_v2_public_export","purpose":"public GitHub export genesis"},"hash":"0eb6a65887fd080d7e3a131254104aee0377033b022fd64e4965621e2f4874ff"}
EOF

cat > "$DEST_REAL/EXPORT_MANIFEST.md" <<EOF
# GitHub Export Manifest

Source: local trinity_v2 workspace (absolute path intentionally omitted)
Exported: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

This folder is a GitHub-safe source export generated by:

\`\`\`bash
bash scripts/export_github.sh
\`\`\`

Excluded by default:

- local git history
- local harness/editor state
- environment files and common secret/key names
- Trinity runtime sessions, local audit history, local state, and memory
- local project registry / memory DB files
- provenance/reference corpora under \`references/\`
- known local project aliases rewritten to generic examples
- \`.ai/audit/events.ndjson\` is reset to a one-line public genesis event

Before publishing, run a final human review for licensing, secrets, and
project-specific paths.
EOF

printf 'exported GitHub folder: %s\n' "$DEST_REAL"
printf 'next:\n'
printf '  cd %q\n' "$DEST_REAL"
printf '  git init\n'
printf '  git status --short\n'
